### ISSUE TITLE
Chart Vertically Resize Issue

### ISSUE THREAD

**Issue by li-xinyang** [vinodrajendran001/RR_Frontend#1]
The workaround can be found at https://github.com/c3js/c3/issues/1450 and the cause is the inline `max-height` style for the chart container. To solve the issue, you need to remove the inline style whenever the chart gets resized OR override the inline style using `!important` in the external stylesheet.

```js
      onresize() {
        // Workaround for vertical non-responsive chart
        $('#chart-container-id').css('max-height', 'none')
      }
```

The issue is not caused by D3, hence, rebuild the library is not going to solve the issue.

**Comment by vinodrajendran001** [comment]
I already read this workaround, but the suggested solutions didn't work in the way that I want. However, your comments sparked me for another and fortunately it works well now.

Now, I have updated the repository with the fix.

Cheers,
Vinod
